name: flutter_cleanup_mcp
description: MCP server for cleaning up unused code in Flutter/Dart projects.
version: 0.0.1
publish_to: none
repository: https://github.com/Code-Growers/flutter_cleanup_mcp
issue_tracker: https://github.com/Code-Growers/flutter_cleanup_mcp/issues
homepage: https://codegrowers.com

environment:
  sdk: ^3.0.0

dependencies:
  args: 2.4.0
  logging: 1.2.0
  mcp_dart: 1.2.1
  vm_service: 15.0.2
  path: 1.9.0
  yaml: 3.1.3

dev_dependencies:
  lints: 6.1.0
  test: 1.29.0
