name: flutter_cleanup_mcp
description: MCP server for cleaning up unused code in Flutter/Dart projects.
version: 0.0.2
repository: https://github.com/Code-Growers/flutter_cleanup_mcp
issue_tracker: https://github.com/Code-Growers/flutter_cleanup_mcp/issues
homepage: https://codegrowers.com

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  logging: ^1.2.0
  mcp_dart: ^1.2.2
  path: ^1.9.0

dev_dependencies:
  lints: 6.1.0
  test: 1.29.0

executables:
  flutter_cleanup_mcp: flutter_cleanup_mcp
